import { PreflightProfile } from '../types';

export const DEFAULT_PROFILES: PreflightProfile[] = [
    {
        id: 'b-w-brochure',
        name: 'profile_bw_brochure',
        bleed: 3,
        safeMargin: 5,
        minPpiColor: 150,
        minPpiGrayscale: 240,
        minPpiLineart: 800,
        allowRgb: false,
        allowSpot: false,
        maxTac: 280,
        minHairline: 0.25,
        requireBlackOverprint: true,
        disallowWhiteOverprint: true,
        allowTransparency: true,
        allowAnnotations: false,
        requireEvenPages: true,
    },
    {
        id: 'color-book-coated',
        name: 'profile_color_book',
        bleed: 3,
        safeMargin: 5,
        minPpiColor: 300,
        minPpiGrayscale: 300,
        minPpiLineart: 1200,
        allowRgb: false,
        allowSpot: true,
        maxTac: 320,
        minHairline: 0.1,
        requireBlackOverprint: true,
        disallowWhiteOverprint: true,
        allowTransparency: false, // Recommends PDF/X-1a
        allowAnnotations: false,
        requireEvenPages: true,
    },
    {
        id: 'web-display',
        name: 'profile_web_display',
        bleed: 0,
        safeMargin: 0,
        minPpiColor: 72,
        minPpiGrayscale: 72,
        minPpiLineart: 300,
        allowRgb: true,
        allowSpot: false,
        maxTac: 400,
        minHairline: 0.5,
        requireBlackOverprint: false,
        disallowWhiteOverprint: false,
        allowTransparency: true,
        allowAnnotations: true,
        requireEvenPages: false,
    }
];
